monolog:
    handlers:
        file_log:
            type: stream
            path: "%kernel.logs_dir%/%kernel.environment%.log"
            level: debug

        syslog_handler:
            level: error
            type: syslog
